### ISSUE TITLE
Suggestion: More Healthbar Options

### ISSUE THREAD

**Issue by IdrisQe** [ToroCraft/ToroHUD#1]
Title says it all, really. It would be especially nice to have an option to only show the healthbar when looking at a mob from a certain distance limit, basically like how the GUI works.
It would also be nice to be able to configure the time it keeps showing if set to show after a mob is damaged temporarily.
The ability to show a small number/number to show numerical health value on the healthbar would also be nice. Perhaps allow Healthbars to have the GUI features of potion effects, armor, and health number, but scaled down.

**Comment by frodare** [comment]
Thanks for sharing your thoughts! Are you talking only about the health bars rendered above entities, or also the the health bar in the GUI?

Either way, the distance configuration is a no-brainier which I will add to the next release.

**Comment by IdrisQe** [comment]
I mean the health bar over enemies, although I suppose much of this could apply to the GUI too if you wanted to add the options (although a lot of this is already in the GUI).

**Comment by frodare** [comment]
I have added distance config in v4.  I do like the idea of adding more information on the health bars, but that is going to be quite a bit more work which means for now I won't be working on that as I am mostly working on another project.

**Comment by Zahkriiven** [comment]
Hello, sorry for commenting on a closed issue but I was about to open one about the same thing. First of all I think this mod is a good replacement for the old [Hit Splat Damage Indicators](https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-mods/1286538-hit-splat-damage-indicators-v3-3-2-rpg-ui-and) and I love the health animations.
However, as mentioned by IdrisQe, I personally don't like a GUI for displaying mob info but instead display over the mob itself. I have been using [Neat](https://minecraft.curseforge.com/projects/neat)  for this. Having things like name and current hp / max hp would be a very nice addition.

**Comment by frodare** [comment]
It would be a fun challenge to get working, I am certainly not against it by any means.  Neat looks like a really cool, I have been meaning to try it out for a while now.  That being said, why are you interested in ToroHUD implementing features Neat already does really well? Maybe for potion effects, damage particles, or maybe looking for more variety? I'm just curious.

**Comment by Zahkriiven** [comment]
Mainly for the damage indicator and the health decreasing animation in the healthbar. It gives it a very cool detail and rpg feel.

**Comment by frodare** [comment]
https://github.com/ToroCraft/ToroHUD/issues/4
