### ISSUE TITLE
healthbar over mobs bug

### ISSUE THREAD

**Issue by diefesson** [ToroCraft/ToroHUD#2]
Selecting "none" in healthbar is the same thing of selection "ever"

**Comment by frodare** [comment]
Please try the latest version (v4) and see if you still have this problem.  If you do, please describe it in more detail and I will look into it further.

**Comment by Zahkriiven** [comment]
Bug confirmed, setting the "Show bars Above Entities" option to "none" always shows them.

**Comment by frodare** [comment]
Oooooh, will look at when I get home.

**Comment by frodare** [comment]
This is fixed in v5

**Comment by diefesson** [comment]
Thanks

Em sex, 5 de out de 2018 8:17 PM, Charles Howard <notifications@github.com>
escreveu:
